language: go

go:
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - wget https://github.com/h12w/gosweep/raw/master/gosweep.sh
  - chmod +x gosweep.sh
install:
    - go get -d -v ./...

script:
    - gosweep.sh
