language: go

go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6

install:
    - go get -d -v ./...

script:
    - go build -v ./...
    - go test -v ./... -coverprofile=coverage.txt -covermode=atomic

codecov:
  token: 904ed379-1635-4df0-a5c1-0e445aae49ba

after_success:
    - bash <(curl -s https://codecov.io/bash)